
export type FieldLabelMap = Record<string, string>;

export const fieldLabelMapsByMaterialType: Record<string, FieldLabelMap> = {
    "น้ำมันดีเซลพื้นฐาน (H-Base)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        bl: "B/L",
        outturn: "Outturn",
        discount: "ปริมาณสิทธิ์หักลดหย่อน",
        tax_rate: "อัตราภาษี",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ Stock",
        remains_report: "ยอดคงเหลือตามบัญชีสิทธิ์",
        diff: "น้ำมัน Gain",
        // "": "หมายเหตุ",        
    },
    "น้ำมันดีเซลหมุนเร็ว (500030)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        bl: "B/L",
        outturn: "Outturn",
        "": "จำนวนรับตามบัญชีสิทธิ์ฯ",
        tax_rate: "อัตราภาษี",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ Stock",
        remains_report: "ยอดคงเหลือตามบัญชีสิทธิ์",
        // "": "หมายเหตุ",        
    },
    "ไบโอดีเซลประเภทเมิทิลเอสเตอร์ของกรดไขมัน (500038)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        bl: "B/L",
        "": "ค้างท่อ",
        outturn: "Outturn",        
        tax_rate: "อัตราภาษี",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ Stock",
        remains_report: "ยอดคงเหลือตามบัญชีสิทธิ์",
        diff: "น้ำมัน Gain",
        // "": "หมายเหตุ",        
    },
    "สารเติมเเต่ง Diesl RE-901J (100991)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        bl: "B/L",
        outturn: "Outturn",        
        tax_rate: "อัตราภาษี",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ Stock",
        remains_report: "ยอดคงเหลือตามบัญชีสิทธิ์",
        diff: "น้ำมัน Gain",
        // "": "หมายเหตุ",        
    },
    "Denatured Ethanol (400003052)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "RBOB 91 -TA (400004531)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        other_product: "ส่งให้คลังต่างจังหวัดผลิตสินค้าอื่น",
        broken: "เสียหาย",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "RBOB 95 -TA (400004491)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "ULG 95 - TA (400004521)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        tax_rate: "ผลิตสินค้าพิกัดอัตราภาษีสรรพสามิต",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "B100 HP (4000010633)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        broken: "เสียหาย",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "Nemo 2500 (220003164/220003191)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "Fuel Oil - TA (400003049)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        tax_rate: "ผลิตสินค้าพิกัดอัตราภาษีสรรพสามิต",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "DYEGUARD BROWN O (220007727/220007750)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        tax_rate: "ผลิตสินค้าพิกัดอัตราภาษีสรรพสามิต",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "Diesel Base - TA (400004540)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        other_loss: "อื่นๆ",
        broken: "เสียหาย",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "NEMO 6164 (220008611/220008690)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "NEMO 2016 (22008581/220008700)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "Fuel Oil - TA (400003048)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        tax_rate: "ผลิตสินค้าพิกัดอัตราภาษีสรรพสามิต",
        other_product: "ผลิตสินค้าอื่น",
        "": "น้ำมันลดคุณค่า",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "D-Tect 66614 ( 22003942/220004101 )": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        other_product: "ผลิตสินค้าอื่น",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "DYE/MARKDYEGREDG_BULK_ZZZZ (22009816)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า", 
        other_product: "ผลิตสินค้าอื่น",
        tax_rate: "ผลิตสินค้าพิกัดอัตราภาษีสรรพสามิต",        
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },
    "OIL PURPLE G LIQUID_BULK_ZZZZ (220009960)": {
        date: "วัน เดือน ปี",
        main_product: "รายการ",
        evidence_number: "หลักฐานเลขที่",
        "": "จำนวนรับ",
        quantity: "ผลิตสินค้า",
        broken: "เสียหาย",
        other_loss: "อื่นๆ",
        total: "รวมจ่าย",
        remains_physical: "ยอดคงเหลือ",
        // "": "หมายเหตุ",        
    },

};

export const commonFieldLabelMap: FieldLabelMap = {
    date: "วัน เดือน ปี",
    main_product: "รายการ",
    evidence_number: "หลักฐานเลขที่",
    bl: "B/L",
    outturn: "Outturn",
    quantity: "ผลิตสินค้า",
    other_product: "ผลิตสินค้าอื่น",
    broken: "เสียหาย",
    other_loss: "อื่นๆ",
    total: "รวมจ่าย",
    remains_physical: "ยอดคงเหลือ",
    // "": "หมายเหตุ",
};

export function getFieldLabelMap(materialType: string): FieldLabelMap {
    for (const key in fieldLabelMapsByMaterialType) {
        if (materialType.includes(key)) {
            return fieldLabelMapsByMaterialType[key];
        }
    }
    return commonFieldLabelMap;
}